"""
NEUREQ Phase 1b: Output Sanitization and Validation
This script acts as a strict parsing filter to clean and validate the raw 
DeepSeek-R1-Distill-Qwen-32B text generations. It isolates the JSON payload 
from chain-of-thought traces and ensures the output strictly adheres to the 
10-question eligibility schema required for Phase 2 re-ranking.
"""

import json

# ==========================================
# GLOBAL FILE PATHS
# ==========================================
# The raw output file generated by neureq_ph1a.py containing unfiltered LLM text
INPUT_JSONL = "data/2021/WholeQ_RM3_RETRIEVAL_T2021_llm_responses.jsonl" 

# The destination file for the strictly parsed and validated outputs
OUTPUT_JSONL = f"{INPUT_JSONL.split('.')[0]}_sanitized.jsonl"
# ==========================================

def clean_generated_text(text, idx):
    """
    Applies aggressive string manipulation to extract a valid JSON dictionary 
    from the raw LLM output and validates its structural integrity.
    
    Args:
        text (str): The raw text generated by the LLM (includes <think> tags).
        idx (int): The line index (used for precise error logging during audits).
        
    Returns:
        dict: The parsed and validated JSON dictionary, or None if validation fails.
    """
    try:
        # Step 1: Strip out DeepSeek's internal chain-of-thought reasoning
        # Everything before and including the closing </think> tag is discarded.
        text = text.split('</think>')[-1]
        
        # Step 2: Locate the start of the JSON object
        # Reconstructs the string starting from the very first opening brace '{'
        text = '{' + '{'.join(text.split('{')[1:])
        
        # Step 3: Locate the end of the JSON object
        # The NEUREQ schema demands exactly 10 questions. This heuristic assumes 
        # a flat JSON structure and truncates the string at the 11th closing brace.
        text = '}'.join(text.split('}')[:11]) + '}'
        
        # Step 4: Attempt to parse the sanitized string into a Python dictionary
        parsed = json.loads(text)

        # Step 5: Strict Schema Validation
        # The downstream BiLSTM expects exactly 10 feature vectors.
        # We must enforce that the parsed object is a dictionary with exactly 10 keys.
        if isinstance(parsed, dict) and len(parsed) == 10:
            return parsed
        else:
            # Log structural failures (e.g., LLM only generated 9 answers)
            print(f"===== Skipping idx: {idx} due to insufficient keys in cleaned_output")
            return None
            
    except Exception as e:
        # Catch standard JSON decoding errors (e.g., unescaped quotes, missing commas)
        print(f"{'='*15} Skipping idx: {idx} due to error: {e}")
        return None

def process_jsonl(input_path, output_path):
    """
    Iterates through the raw LLM responses, applies the cleaning heuristics, 
    and writes out a standardized, downstream-ready JSONL file.
    
    Args:
        input_path (str): Path to the raw LLM responses JSONL.
        output_path (str): Path to save the sanitized dataset.
    """
    with open(input_path, 'r', encoding='utf-8') as infile, open(output_path, 'w', encoding='utf-8') as outfile:
        # Read the raw file line by line to maintain a low memory footprint
        for idx, line in enumerate(infile):
            try:
                # Load the current entry
                data = json.loads(line)
                
                # Re-run the aggressive cleaning logic explicitly on the raw "result" text
                cleaned = clean_generated_text(data.get("result"), idx)
                
                # Construct the finalized object. Note that the bulky raw "result" 
                # string is intentionally dropped here to save disk space and simplify data.
                out_data = {
                        "qid": data.get("qid"),
                        "docid": data.get("docid"),
                        "cleaned_output": cleaned # Will be 'None' if parsing failed
                }
                
                # Write the sanitized entry to the new file
                outfile.write(json.dumps(out_data) + '\n')
                
            except Exception as e:
                print(f"Error processing line: {e}")

if __name__ == "__main__":
    # Execute the processing pipeline
    process_jsonl(INPUT_JSONL, OUTPUT_JSONL)