import os
import json
import random
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from tqdm import tqdm
import logging
from sklearn.metrics import roc_auc_score

# ============================================================
# CONFIGURATION & HYPERPARAMETERS
# ============================================================

# The synthetic triplet dataset created for training the Phase 2 reranker
INPUT_FILE = "dataset/triplet_syn_dataset_1196.jsonl"

# Output directory for saving model checkpoints and logs
OUTPUT_DIR = "models_new/BiLSTM_ADD_ATTN_1196"
os.makedirs(OUTPUT_DIR, exist_ok=True)

LOG_FILE = os.path.join(OUTPUT_DIR, "training_log.txt")

# Training hyperparameters
MAX_EPOCHS = 30
BATCH_SIZE = 16
LEARNING_RATE = 2e-4
TRAIN_SPLIT = 0.8 # 80/20 Train-Validation split
RANDOM_SEED = 42

# Hardware configuration
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# ============================================================
# LOGGING
# ============================================================

# Configure logging to output to both the console and a text file for auditing
logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler(LOG_FILE, mode="w")
    ]
)

# ============================================================
# CLINICALBERT (FROZEN TEXT ENCODER)
# ============================================================

# Initialize Bio_ClinicalBERT to encode the natural language justifications.
# We freeze this model (eval mode, no_grad) because fine-tuning a BERT model 
# alongside a BiLSTM would cause severe memory overhead and over-fitting on small data.
CLINICAL_BERT_MODEL = "emilyalsentzer/Bio_ClinicalBERT"
tokenizer = AutoTokenizer.from_pretrained(CLINICAL_BERT_MODEL)
bert_model = AutoModel.from_pretrained(CLINICAL_BERT_MODEL).to(DEVICE)
bert_model.eval()

@torch.no_grad()
def encode_justification(text: str):
    """
    Converts a natural language justification into a dense semantic vector.
    
    Args:
        text (str): The text justification generated by the Phase 1 LLM.
        
    Returns:
        torch.Tensor: The 768-dimensional [CLS] token embedding.
    """
    inputs = tokenizer(
        text,
        truncation=True,
        padding="max_length",
        max_length=128,
        return_tensors="pt"
    ).to(DEVICE)

    outputs = bert_model(**inputs)
    # Extract the [CLS] token representing the sentence-level semantic summary
    return outputs.last_hidden_state[:, 0, :].squeeze(0)  

# ============================================================
# DATASET AND DATALOADER
# ============================================================

# Map the categorical ternary answers to integer indices for PyTorch Embedding layers
ANSWER_MAP = {"YES": 0, "NO": 1, "NA": 2}

class EligibilityDataset(Dataset):
    """
    PyTorch Dataset wrapper to format the JSONL data into tensors.
    Transforms the 10-question structured outputs into sequences.
    """
    def __init__(self, samples):
        self.samples = samples

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        item = self.samples[idx]

        question_ids = []
        answer_ids = []
        justification_embs = []

        # Iterate through exactly 10 questions (1-indexed in the JSON)
        for qid in range(1, 11):
            q = item["output"][str(qid)]

            # Convert to 0-indexed for Embedding layer compatibility (0-9)
            question_ids.append(qid - 1)
            # Map "YES", "NO", "NA" to integers (0-2)
            answer_ids.append(ANSWER_MAP[q["response"]])

            # Process the justification text into a 768-dim tensor
            just_text = q.get("justification", "")
            justification_embs.append(encode_justification(just_text))

        # Binary label: 1 if trial is relevant, 0 if it is a hard negative
        label = 1 if item["label"] == "positive" else 0

        return (
            torch.tensor(question_ids, dtype=torch.long),
            torch.tensor(answer_ids, dtype=torch.long),
            torch.stack(justification_embs),
            torch.tensor(label, dtype=torch.float)
        )

# ============================================================
# MODEL ARCHITECTURE
# ============================================================

class AdditiveAttention(nn.Module):
    """
    Computes importance weights over the 10 eligibility questions.
    This layer is critical for interpretability, allowing feature-level 
    attribution to see which clinical criteria drove the final ranking.
    """
    def __init__(self, hidden_dim):
        super().__init__()
        self.attn = nn.Linear(hidden_dim, hidden_dim)
        self.v = nn.Linear(hidden_dim, 1, bias=False)

    def forward(self, H):
        # H shape: (Batch, Sequence_Length, Hidden_Dim)
        scores = self.v(torch.tanh(self.attn(H))).squeeze(-1)
        # alpha shape: (Batch, Sequence_Length) - The attention weights
        alpha = torch.softmax(scores, dim=1)
        # context shape: (Batch, Hidden_Dim) - The weighted sum of the sequence
        context = torch.sum(alpha.unsqueeze(-1) * H, dim=1)
        return context, alpha

class EligibilityBiLSTM(nn.Module):
    """
    The core Phase 2 Neural Re-ranker. Models the forward and backward 
    dependencies between clinical eligibility questions to assess overall relevance.
    """
    def __init__(self):
        super().__init__()

        # Low-dimensional learnable embeddings for structural identifiers
        self.question_embed = nn.Embedding(10, 8) # Maps 10 questions to 8 dims
        self.answer_embed = nn.Embedding(3, 3)    # Maps 3 answers to 3 dims

        # BiLSTM processes the concatenated feature sequence
        # Input size: 8 (question) + 3 (answer) + 768 (justification) = 779
        self.bilstm = nn.LSTM(
            input_size=8 + 3 + 768,
            hidden_size=64,
            num_layers=1,
            bidirectional=True, # Captures relationships from preceding and subsequent criteria
            batch_first=True
        )

        # Output of BiLSTM is 64 * 2 (bidirectional) = 128
        self.attention = AdditiveAttention(128)

        # Feed-forward classifier to predict final relevance score
        self.classifier = nn.Sequential(
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Dropout(0.3), # Regularization to prevent overfitting
            nn.Linear(64, 1) # Outputs a single unnormalized logit
        )

    def forward(self, q_ids, a_ids, j_embs):
        """
        Defines the forward pass of the network.
        """
        # Embed categorical inputs
        q_emb = self.question_embed(q_ids)
        a_emb = self.answer_embed(a_ids)

        # Concatenate question ID, categorical answer, and text embeddings
        x = torch.cat([q_emb, a_emb, j_embs], dim=-1)
        
        # Process sequential dependencies
        H, _ = self.bilstm(x)

        # Compute attention-weighted context vector
        context, attn_weights = self.attention(H)
        
        # Predict relevance logit
        logit = self.classifier(context).squeeze(-1)

        # Return both the prediction and the attention weights for later interpretability analysis
        return logit, attn_weights

# ============================================================
# TRAINING LOOP
# ============================================================

def train():
    """
    Executes the main training pipeline: loads data, instantiates the model, 
    iterates through epochs, calculates loss/AUC, and saves checkpoints.
    """
    # 1. Load the synthetic training data
    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        all_samples = [json.loads(line) for line in f]

    # Ensure reproducibility for academic auditing
    random.seed(RANDOM_SEED)
    random.shuffle(all_samples)

    # 2. Perform Train/Validation split
    split_idx = int(len(all_samples) * TRAIN_SPLIT)
    train_samples = all_samples[:split_idx]
    val_samples = all_samples[split_idx:]

    logging.info(f"Total samples : {len(all_samples)}")
    logging.info(f"Train samples : {len(train_samples)}")
    logging.info(f"Val samples   : {len(val_samples)}")

    # 3. Initialize PyTorch DataLoaders
    train_loader = DataLoader(
        EligibilityDataset(train_samples),
        batch_size=BATCH_SIZE,
        shuffle=True
    )

    val_loader = DataLoader(
        EligibilityDataset(val_samples),
        batch_size=BATCH_SIZE
    )

    # 4. Initialize model, optimizer, and loss function
    model = EligibilityBiLSTM().to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)
    # Using BCEWithLogitsLoss combines a Sigmoid layer and BCELoss in one numerically stable class
    criterion = nn.BCEWithLogitsLoss() 

    best_val_loss = float("inf")
    best_epoch = -1

    # 5. Execute Epochs
    for epoch in range(1, MAX_EPOCHS + 1):
        
        # --- TRAIN PHASE ---
        model.train()
        train_loss = 0.0

        for q_ids, a_ids, j_embs, labels in tqdm(
            train_loader, desc=f"Epoch {epoch} [Train]"
        ):
            # Move batch to GPU
            q_ids, a_ids = q_ids.to(DEVICE), a_ids.to(DEVICE)
            j_embs, labels = j_embs.to(DEVICE), labels.to(DEVICE)

            # Standard PyTorch training step
            optimizer.zero_grad()
            logits, _ = model(q_ids, a_ids, j_embs)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()

        train_loss /= len(train_loader)

        # --- VALIDATION PHASE ---
        model.eval()
        val_loss = 0.0
        all_val_logits = []
        all_val_labels = []

        # Disable gradient calculation for evaluation to save memory
        with torch.no_grad():
            for q_ids, a_ids, j_embs, labels in val_loader:
                q_ids, a_ids = q_ids.to(DEVICE), a_ids.to(DEVICE)
                j_embs, labels = j_embs.to(DEVICE), labels.to(DEVICE)

                logits, _ = model(q_ids, a_ids, j_embs)
                loss = criterion(logits, labels)

                val_loss += loss.item()
                all_val_logits.append(logits.detach().cpu())
                all_val_labels.append(labels.detach().cpu())

        val_loss /= len(val_loader)

        # Calculate Area Under the ROC Curve (AUC) for evaluating binary classification performance
        all_val_logits = torch.cat(all_val_logits).numpy()
        all_val_labels = torch.cat(all_val_labels).numpy()
        val_auc = roc_auc_score(all_val_labels, all_val_logits)

        # Log metrics
        logging.info(
            f"Epoch {epoch:02d} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val Loss: {val_loss:.4f} | "
            f"Val AUC: {val_auc:.4f}"
        )

        # --- CHECKPOINTING ---
        # Save model weights at every epoch for later selection or early-stopping analysis
        ckpt_path = os.path.join(
            OUTPUT_DIR, f"model_epoch_{epoch:02d}.pt"
        )
        torch.save(model.state_dict(), ckpt_path)

        # Track the best performing model based on validation loss
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch = epoch

    logging.info(
        f"Training completed. Best validation loss = {best_val_loss:.4f} "
        f"at epoch {best_epoch}."
    )

if __name__ == "__main__":
    train()