# mft5_2.py

"""
Baseline Model: MFT-MonoT5 (Step 2/4) - Retrieval & Reciprocal Rank Fusion (RRF)

Objective:
    This script executes the retrieval and fusion step for the MFT-MonoT5 baseline. 
    In Step 1, we generated 40 synthetic queries for every patient case. Here, we 
    search the clinical trial index for all of those synthetic queries (and optionally 
    the original patient description). 
    
    Because search scores from different queries are not on the same scale, we cannot 
    simply average them. Instead, we use Reciprocal Rank Fusion (RRF) to merge the 
    resulting ranked lists based on their rank positions, producing a single, highly 
    robust top-100 candidate list for each patient topic.
"""

import os
import pandas as pd
from tqdm import tqdm
from pyserini.search.lucene import LuceneSearcher
from collections import defaultdict

# =============================================================================
# CONFIGURATION & FILE PATHS
# =============================================================================
# The pre-built Pyserini Lucene index containing the 448k+ clinical trials
index_dir = "indexes/clinical_trials"

# Inputs: The outputs from Step 1 and the original patient descriptions
# Ensure the year aligns with your evaluation target (e.g., 2021 or 2022)
synthetic_queries_file = "data/2021/synthetic_queries_2021.tsv"
patient_desc_file      = "data/2021/ct_2021_queries.tsv"

# Outputs: The fused candidate lists in standard TREC format.
# We generate 4 variants to thoroughly evaluate the baseline under different settings:
# 1. BM25 using only Synthetic Queries
output_bm25_nqs    = "data/2021/bm25_rrf_nqs.txt"
# 2. BM25+RM3 using only Synthetic Queries
output_rm3_nqs     = "data/2021/bm25rm3_rrf_nqs.txt"
# 3. BM25 using Synthetic Queries AND the original Patient Description (PD)
output_bm25_nqs_pd = "data/2021/bm25_rrf_nqs_pd.txt"
# 4. BM25+RM3 using Synthetic Queries AND the original Patient Description (PD)
output_rm3_nqs_pd  = "data/2021/bm25rm3_rrf_nqs_pd.txt"

# --- Retrieval Hyperparameters ---
hits = 100   # Number of trials to retrieve per individual query before fusion
rrf_k = 60   # RRF smoothing constant. 60 is the industry standard (Cormack et al., 2009)

# =============================================================================
# INITIALIZE SEARCHERS (PySerini)
# =============================================================================
# Searcher 1: Standard BM25 (Lexical matching)
bm25_searcher = LuceneSearcher(index_dir)
# k1 controls term frequency saturation; b controls document length normalization
bm25_searcher.set_bm25(k1=0.9, b=0.4)

# Searcher 2: BM25 + RM3 (Pseudo-Relevance Feedback)
# RM3 expands the query using terms from the top retrieved documents, improving recall.
rm3_searcher = LuceneSearcher(index_dir)
rm3_searcher.set_bm25(k1=0.9, b=0.4)
rm3_searcher.set_rm3(
    fb_terms=10,             # Add the 10 most informative terms from the top docs
    fb_docs=10,              # Assume the top 10 retrieved docs are relevant for feedback
    original_query_weight=0.5 # Balance the original query vs the new feedback terms (50/50)
)

# =============================================================================
# DATA LOADING
# =============================================================================
# Load the 40 synthetic queries per topic generated by baseline_mft5_1.py
df_syn = pd.read_csv(synthetic_queries_file, sep="\t")

# Load the original, lengthy patient case descriptions
df_pd = pd.read_csv(patient_desc_file, sep="\t", header=None, names=["topic_id", "patient_description"])

# --- Structure the Synthetic Queries ---
query_list_nqs = []
for _, row in df_syn.iterrows():
    topic_id = str(row["topic_id"])
    syn_query = row["synthetic_query"]
    # Create a unique sub-ID for each of the 40 synthetic queries attached to this topic
    # e.g., "1-syn-1", "1-syn-2", etc.
    query_id = f"{topic_id}-syn-{len([q for q in query_list_nqs if q[0] == topic_id]) + 1}"
    query_list_nqs.append((topic_id, query_id, syn_query))

# --- Structure the Original Patient Descriptions ---
query_list_pd = []
for _, row in df_pd.iterrows():
    topic_id = str(row["topic_id"])
    pd_query = row["patient_description"]
    # Create a unique sub-ID for the original case
    query_id = f"{topic_id}-pd"
    query_list_pd.append((topic_id, query_id, pd_query))


# =============================================================================
# RETRIEVAL & FUSION ENGINE
# =============================================================================
def run_and_fuse(searcher, run_id, out_file, query_list, extra_queries=None):
    """
    Executes searches for a list of queries, applies Reciprocal Rank Fusion, 
    and exports the final top-100 list to disk.
    """
    if extra_queries is None:
        extra_queries = []

    # Combine all query variants (e.g., 40 synthetic + 1 original = 41 queries per topic)
    full_query_list = query_list + extra_queries
    
    # Dictionary to store raw retrieval scores: {query_id: {doc_id: score}}
    all_runs = defaultdict(dict)  

    # --- Phase A: Individual Retrieval ---
    print(f"\nRunning {run_id} on queries ({len(full_query_list)} total)...")
    # LOOP EXPLANATION: Execute a separate Lucene search for every single query variant.
    for topic_id, query_id, query_text in tqdm(full_query_list):
        hits_list = searcher.search(query_text, k=hits)
        for rank, hit in enumerate(hits_list):
            all_runs[query_id][hit.docid] = hit.score

    # --- Phase B: Reciprocal Rank Fusion (RRF) ---
    print(f"Applying RRF fusion per topic for {run_id}...")
    # Stores the final fused score for each document under each topic
    topic_results = defaultdict(dict)

    # LOOP EXPLANATION: Iterate through the retrieval results and apply the RRF formula.
    # Formula: RRF_Score(doc) = Sum( 1 / (k + Rank_in_Query_i) )
    for topic_id, query_id, query_text in full_query_list:
        # Sort the documents retrieved for this specific sub-query by their BM25 score
        sorted_docs = sorted(all_runs[query_id].items(), key=lambda x: x[1], reverse=True)
        
        for rank, (doc_id, score) in enumerate(sorted_docs, start=1):
            # Add the reciprocal of the rank to the document's global topic score.
            # If a document appears high up in multiple synthetic queries, its RRF score compounds.
            topic_results[topic_id][doc_id] = topic_results[topic_id].get(doc_id, 0) + 1.0 / (rrf_k + rank)

    # --- Phase C: Export ---
    print(f"Saving fused results to {out_file}...")
    with open(out_file, "w") as f:
        for topic_id, doc_scores in topic_results.items():
            # Sort the final fused pool and strictly truncate to the top 100 trials
            ranked_docs = sorted(doc_scores.items(), key=lambda x: x[1], reverse=True)[:100]
            
            for rank, (doc_id, score) in enumerate(ranked_docs, start=1):
                # Write to standard TREC format: topic_id Q0 trial_id rank score run_name
                f.write(f"{topic_id} Q0 {doc_id} {rank} {score:.4f} {run_id}\n")

# =============================================================================
# EXECUTION
# =============================================================================
# Run all four permutations to generate candidate pools for the neural re-ranker (Step 3).

# 1. BM25 with just Synthetic Queries
run_and_fuse(bm25_searcher, "bm25_nqs",        output_bm25_nqs,    query_list_nqs)
# 2. BM25+RM3 with just Synthetic Queries
run_and_fuse(rm3_searcher,  "bm25rm3_nqs",     output_rm3_nqs,     query_list_nqs)

# 3. BM25 with Synthetic Queries + Original Patient Description
run_and_fuse(bm25_searcher, "bm25_nqs_pd",     output_bm25_nqs_pd, query_list_nqs, extra_queries=query_list_pd)
# 4. BM25+RM3 with Synthetic Queries + Original Patient Description
run_and_fuse(rm3_searcher,  "bm25rm3_nqs_pd",  output_rm3_nqs_pd,  query_list_nqs, extra_queries=query_list_pd)

print("\n✅ Retrieval + RRF complete for NQS, PD, BM25, and BM25+RM3!")