# mft5_4.py

"""
Baseline Model: MFT-MonoT5 (Step 4/4) - Max-Pooling Aggregation

Objective:
    This script finalizes the MFT-MonoT5 baseline evaluated in Section 4.2 of 
    the NEUREQ paper. 
    
    In Step 3, the MonoT5 model evaluated the relevance of overlapping 6-sentence 
    segments extracted from the clinical trials. This script ingests those millions 
    of segment-level scores and aggregates them into a single document-level score 
    for each patient-trial pair using the "MaxP" (Max-Pooling) heuristic. It then 
    exports the final sorted rankings in the official TREC format.
"""

import json
import pandas as pd
from collections import defaultdict
from tqdm import tqdm

# =============================================================================
# CONFIGURATION & FILE PATHS
# =============================================================================
# --- Input ---
# The JSONL cache file generated by Step 3 containing the individual segment scores.
# You should update this path to match the specific retrieval run you are evaluating.
segment_scores_file = "data/2022/sigir/segment_scores_WholeQ_RM3_T2022.jsonl"  

# --- Output ---
# The final TREC-formatted run file ready to be evaluated by `trec_eval` and `ttest.py`.
output_run_file     = "data/2022/sigir/monot5_rerank_WholeQ_RM3_T2022.txt"    

# The system tag that will appear in the 6th column of the TREC run file.
run_id              = "MonoT5-3B-BM25RM3-NQS-PD"                             

# Restrict the final output to the top 100 trials per query (Standard TREC Track limit)
topk                = 100                                            

# =============================================================================
# LOAD AND AGGREGATE SEGMENT SCORES (MaxP Algorithm)
# =============================================================================
print(f"Loading segment scores from {segment_scores_file} ...")

# Nested dictionary to store the maximum score found for each patient-trial pair:
# Structure: { topic_id: { trial_id: highest_segment_score } }
trial_scores = defaultdict(dict)  

with open(segment_scores_file, "r") as f:
    # LOOP EXPLANATION: Read the massive JSONL cache line-by-line
    for line in tqdm(f, desc="Reading JSONL"):
        obj = json.loads(line)
        topic_id = str(obj["topic_id"])
        trial_id = obj["trial_id"]
        score = float(obj["score"])

        # THE MAX-POOLING (MaxP) LOGIC:
        # If this is the first time we are seeing this trial for this topic, store the score.
        if trial_id not in trial_scores[topic_id]:
            trial_scores[topic_id][trial_id] = score
        # If we already have a score for this trial, keep whichever segment scored higher.
        # Rationale: A trial is considered highly relevant if AT LEAST ONE specific 
        # eligibility/description segment strongly matches the patient case, even if 
        # the rest of the document is generic boilerplate.
        else:
            trial_scores[topic_id][trial_id] = max(trial_scores[topic_id][trial_id], score)

print(f"✅ Aggregated scores for {len(trial_scores)} topics.")

# =============================================================================
# EXPORT TO TREC FORMAT
# =============================================================================
print(f"Writing run file → {output_run_file}")

with open(output_run_file, "w") as fout:
    # LOOP EXPLANATION: Iterate through the topics, sorting them numerically for clean output
    for topic_id in sorted(trial_scores.keys(), key=lambda x: int(x)):
        
        # Sort the trials for this specific topic by their MaxP score in descending order.
        # Slice the list to retain only the top `topk` (100) trials.
        sorted_trials = sorted(trial_scores[topic_id].items(), key=lambda x: x[1], reverse=True)[:topk]

        # LOOP EXPLANATION: Write each retained trial to the text file
        for rank, (trial_id, score) in enumerate(sorted_trials, start=1):
            # Standard TREC format: <query_id> <iteration> <document_id> <rank> <score> <run_id>
            # Q0 is a legacy TREC iteration string (ignored by modern evaluators but structurally required).
            fout.write(f"{topic_id} Q0 {trial_id} {rank} {score:.6f} {run_id}\n")

print(f"🎯 Done! Saved reranked run to {output_run_file}")